---
# This workflow requires a GALAXY_API_KEY secret present in the GitHub
# repository or organization.
#
# See: https://docs.ansible.com/ansible/latest/collections_guide/collections_publishing.html

name: Release
"on":
  push:
    tags:
      - "*"

defaults:
  run:
    working-directory: "badsectorlabs.ludus_windows_utils"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: "badsectorlabs.ludus_windows_utils"

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Ansible.
        run: pip3 install ansible-core

      - name: Build and publish collection to Galaxy.
        run: |
          ansible-galaxy collection build --force
          ansible-galaxy collection publish *.tar.gz --api-key ${{ secrets.GALAXY_API_KEY }}
